function mobileCaption(){jQuery(function($){if($('#homeCarousel').length&&$('.mobile-carousel-caption .mobile-caption-content').length){var home_caro=$('#homeCarousel');var mobile_caption=$('.mobile-carousel-caption');var mobile_content=mobile_caption.find('.mobile-caption-content');var captions=home_caro.find('.carousel-caption');mobile_caption.removeAttr('data-initiated');mobile_content.find('.carousel-caption').css('position','relative');if(captions.length&&mobile_caption.length){if(mobile_content.children().length==0){captions.clone().appendTo(mobile_content);}
captions.hide();if(!mobile_caption.attr('data-initiated')&&mobile_caption.attr('data-initiated')!='1'){mobile_caption.css('height',mobile_content.height());mobile_caption.attr('data-initiated','1');mobile_content.find('.carousel-caption').css('position','absolute');disable($('.mobile-caption-content .carousel-caption'));enable($(mobile_content.find('.carousel-caption').eq(0)));mobile_caption.attr('onclick',home_caro.find('.item').eq(0).attr('onclick'));home_caro.on('slide.bs.carousel',function(evt){disable($('.mobile-caption-content .carousel-caption'));});home_caro.on('slid.bs.carousel',function(evt){var index=$(evt.relatedTarget).index();disable($('.mobile-caption-content .carousel-caption'));enable($(mobile_content.find('.carousel-caption').eq(index)));mobile_caption.attr('onclick',home_caro.find('.item').eq(index).attr('onclick'));});var pos_diff=-1;home_caro.find('.carousel-inner .item').on('touchstart',function(evt){pos_diff=evt.originalEvent.touches[0].pageX;e.preventDefault();}).on('touchend',function(evt){var posX=evt.originalEvent.changedTouches[0].pageX;if(pos_diff>-1){pos_diff=Math.abs(pos_diff-posX);}
if(pos_diff<5){$(this).trigger('click');}});}}
function disable(elements){$(elements).each(function(){var element=$(this);$(element).removeClass('active');});}
function enable(elements){$(elements).each(function(index){var element=$(this);if(!element.hasClass('active'))$(element).addClass('active');});}}});}
if($('.carousel').length){var caro=$('.carousel');caro.swipe({swipe:function(event,direction,distance,duration,fingerCount,fingerData){if(direction=='left')$(this).carousel('next');if(direction=='right')$(this).carousel('prev');},allowPageScroll:"vertical"});}
function updateBoxDimension(){var $carouselSize=$('.carousel-inner');var $captionSize=$('.carousel-caption');var captionLeft,captionTop;$(".carousel-inner").css('margin-top',"-"+$('.navbar-laptop').outerHeight()+"px");captionLeft=parseInt($('.container').css('padding-left'))+parseInt($('.container').css('margin-left'));captionTop=(($carouselSize.height()/2)-($captionSize.height()/2));$captionSize.css({left:captionLeft,top:captionTop});var home_caro=$('#homeCarousel');var mobile_caption=$('.mobile-carousel-caption');var mobile_content=mobile_caption.find('.mobile-caption-content');var captions=home_caro.find('.carousel-caption');captions.show();}
$(function(){mobileDesktopVariation();});var $item=$('.carousel .item');var $wHeight=$(window).height();var $src;$item.eq(0).addClass('active');$item.height($wHeight);$item.addClass('full-screen');function mobileDesktopVariation(){if(window.innerWidth>=1024){$(".carousel-inner").css('margin-top',"-"+$('.navbar-laptop').outerHeight()+"px");$(updateBoxDimension);$('.carousel img').each(function(){$src=$(this).attr('src');var $color=$(this).attr('data-color');$(this).parent().css({'background-image':'url('+$src+')','background-color':$color});$(this).remove();});updateBoxDimension();}else{updateBoxDimension();mobileCaption();$(".carousel-inner").css('top',"0px");$('.carousel-caption').css({left:'0',top:'0'});}}
$(window).on('resize',function(){mobileDesktopVariation();$item=$('.carousel .item');$wHeight=$(window).height();$src;$item.eq(0).addClass('active');$item.height($wHeight);$item.addClass('full-screen');$wHeight=$(window).height();$item.height($wHeight);});function isScrolledIntoView(elem){var docViewTop=$(window).scrollTop();var docViewBottom=docViewTop+$(window).height();var elemTop=$(elem).offset().top;var elemBottom=elemTop+$(elem).height();return((elemBottom<=docViewBottom)&&(elemTop>=docViewTop));}
function Utils(){}
Utils.prototype={constructor:Utils,isElementInView:function(element,fullyInView){var pageTop=$(window).scrollTop();var pageBottom=pageTop+$(window).height();var elementTop=$(element).offset().top;var elementBottom=elementTop+$(element).height();if(fullyInView===true){return((pageTop<elementTop)&&(pageBottom>elementBottom));}else{return((elementTop<=pageBottom)&&(elementBottom>=pageTop));}}};var Utils=new Utils();